### ISSUE TITLE
Can't get token

### ISSUE THREAD

**Issue by sovietspy2** [PatriceVignola/skype-web-api#2]
Is that possible that the API has changed? 
I followed the instructions but I get this error:
```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at FormData._getContentDisposition (C:\Users\Soviet\Documents\js\skypeBot\node_modules\form-data\lib\form_data.js:226:40)
    at FormData._multiPartHeader (C:\Users\Soviet\Documents\js\skypeBot\node_modules\form-data\lib\form_data.js:177:33)
    at FormData.append (C:\Users\Soviet\Documents\js\skypeBot\node_modules\form-data\lib\form_data.js:70:21)
    at appendFormValue (C:\Users\Soviet\Documents\js\skypeBot\node_modules\request\request.js:326:21)
    at Request.init (C:\Users\Soviet\Documents\js\skypeBot\node_modules\request\request.js:337:11)
    at Request.RP$initInterceptor [as init] (C:\Users\Soviet\Documents\js\skypeBot\node_modules\request-promise-core\configure\request2.js:45:29)
    at new Request (C:\Users\Soviet\Documents\js\skypeBot\node_modules\request\request.js:127:8)
    at request (C:\Users\Soviet\Documents\js\skypeBot\node_modules\request\index.js:53:10)
    at Function.post (C:\Users\Soviet\Documents\js\skypeBot\node_modules\request\index.js:61:12)
    at _callee3$ (C:\Users\Soviet\Documents\js\skypeBot\node_modules\skype-web-api\lib\api\generateSkypeToken.js:165:51)
(node:17824) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17824) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by JCole45** [comment]
I get the error below:

`TypeError: Cannot read property 'key' of undefined
[1]     at /node_modules/skype-web-api/lib/api/generateSkypeToken.js:51:26
[1]     at Array.forEach (<anonymous>)
[1]     at _callee$ (/node_modules/skype-web-api/lib/api/generateSkypeToken.js:50:21)
[1]     at tryCatch (/node_modules/regenerator-runtime/runtime.js:62:40)
[1]     at Generator.invoke [as _invoke] (/node_modules/regenerator-runtime/runtime.js:296:22)
[1]     at Generator.prototype.<computed> [as next] (/node_modules/regenerator-runtime/runtime.js:114:21)
[1]     at step (/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
[1]     at /node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
[1]     at runMicrotasks (<anonymous>)
[1]     at processTicksAndRejections (internal/process/task_queues.js:95:5)`
